export const CUSTOMER_LIST_LOADING = 'CUSTOMER_LIST_LOADING';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_ERROR = 'CUSTOMER_LIST_ERROR';
export const CUSTOMER_LIST_RESET = 'CUSTOMER_LIST_RESET';
