checks:
  javascript: true
build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
filter:
  excluded_paths:
    - 'client/legacy/static'
    - 'client/legacy/src/store'
    - 'client/kit/static'
