export const AUTH_AUTHENTICATION_LOADING = 'AUTH_AUTHENTICATION_LOADING';
export const AUTH_AUTHENTICATION_ERROR = 'AUTH_AUTHENTICATION_ERROR';
export const AUTH_AUTHENTICATION_RESET = 'AUTH_AUTHENTICATION_RESET';
export const AUTH_AUTHENTICATION_LOGOUT = 'AUTH_AUTHENTICATION_LOGOUT';
export const AUTH_AUTHENTICATION_SUCCESS = 'AUTH_AUTHENTICATION_SUCCESS';
