- name: Provision-time setup
  tags: provision
  block:
  - name: Update system
    apt: update_cache=yes
    become: true
  
  - name: Ensure {{ item }} is installed
    apt: name={{ item }} state=present
    with_items:
      - curl
      - git
      - make
    become: true

  - name: Setup Node
    # Use nvm to be able to install a specific Node version.
    import_role:
      name: nvm

  - name: Ensure nginx is installed and up to date
    apt: name=nginx state=latest
    become: true

  - name: Setup certbot
    import_role:
      name: certbot

  - name: Ensure supervisor is installed
    apt: name=supervisor state=present
    become: true

- name: Deploy-time setup
  tags: deploy
  block:
  - name: Ensure nginx is running
    service: name=nginx state=started
    become: true

  - name: Ensure supervisor is running
    service: name=supervisor state=started enabled=yes
    become: true
