export const PROJECT_LIST_LOADING = 'PROJECT_LIST_LOADING';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR';
export const PROJECT_LIST_RESET = 'PROJECT_LIST_RESET';
