export const CORE_LIST_LOADING = 'CORE_LIST_LOADING';
export const CORE_LIST_SUCCESS = 'CORE_LIST_SUCCESS';
export const CORE_LIST_ERROR = 'CORE_LIST_ERROR';
export const CORE_LIST_RESET = 'CORE_LIST_RESET';
