export const CORE_SHOW_LOADING = 'CORE_SHOW_LOADING';
export const CORE_SHOW_SUCCESS = 'CORE_SHOW_SUCCESS';
export const CORE_SHOW_ERROR = 'CORE_SHOW_ERROR';
export const CORE_SHOW_RESET = 'CORE_SHOW_RESET';
