export const CORE_UPSERT_LOADING = 'CORE_UPSERT_LOADING';
export const CORE_UPSERT_SUCCESS = 'CORE_UPSERT_SUCCESS';
export const CORE_UPSERT_ERROR = 'CORE_UPSERT_ERROR';
export const CORE_UPSERT_RESET = 'CORE_UPSERT_RESET';
