export const ACTIVITY_LIST_LOADING = 'ACTIVITY_LIST_LOADING';
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS';
export const ACTIVITY_LIST_ERROR = 'ACTIVITY_LIST_ERROR';
export const ACTIVITY_LIST_RESET = 'ACTIVITY_LIST_RESET';
