- name: Ensure legacy ormconfig.json is absent
  file:
    path: "{{ workdir }}/server/ormconfig.json"
    state: absent
  become: true

- name: Ensure migrations are up to date
  shell:
    cmd: make database-migrate
    chdir: "{{ workdir }}"
  register: migrate
  changed_when: "'migrations are new migrations' in migrate.stdout"
