- name: Ensure supervisor configuration is up to date
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/supervisor.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure server is running
  supervisorctl: name=server state=present
  become: true
  notify: reload nginx

- name: Ensure supervisor has reloaded
  service: name=supervisor state=reloaded
  become: true
