- name: Ensure supervisor configuration is up to date
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/supervisor.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure api is running
  supervisorctl: name=api state=present
  become: true
  notify: reload nginx

- name: Ensure client-legacy is running
  supervisorctl: name=client-legacy state=present
  become: true
  notify: reload nginx

- name: Ensure client-kit is running
  supervisorctl: name=client-kit state=present
  become: true
  notify: reload nginx

- name: Ensure supervisor has reloaded
  service: name=supervisor state=reloaded
  become: true
