export const TASK_LIST_LOADING = 'TASK_LIST_LOADING';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_ERROR = 'TASK_LIST_ERROR';
export const TASK_LIST_RESET = 'TASK_LIST_RESET';
