export const TASK_UPSERT_LOADING = 'TASK_UPSERT_LOADING';
export const TASK_UPSERT_SUCCESS = 'TASK_UPSERT_SUCCESS';
export const TASK_UPSERT_ERROR = 'TASK_UPSERT_ERROR';
export const TASK_UPSERT_RESET = 'TASK_UPSERT_RESET';
