- name: Ensure snapd is installed
  package: name=snapd state=present
  become: true
  register: snapd_install

- name: Ensure snapd is enabled
  systemd: name=snapd.socket enabled=true state=started
  become: true

- name: Update snap after install
  shell: snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: snapd_install is changed
  become: true

- name: Ensure certbot is installed and up to date
  snap: name=certbot classic=yes state=present
  become: true

- name: Symlink certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  become: true
